#!/bin/bash
# sysreport.sh - System Information Report
# COMP2137 Assignment 1

# Identity
HOST=$(hostname)
REPUSER=$(whoami)
DATETIME=$(date "+%Y-%m-%d %H:%M:%S")

# OS
source /etc/os-release
OS=$PRETTY_NAME

# Uptime
UP=$(uptime -p)

# CPU
CPU=$(grep "model name" /proc/cpuinfo | head -1 | cut -d: -f2 | sed 's/^ //')

# RAM
RAM=$(grep MemTotal /proc/meminfo | awk '{printf "%.1f GB", $2/1024/1024}')

# Disks - only physical disks (type disk), skip loop/rom devices
DISKS=$(lsblk -d -o NAME,SIZE,MODEL,TYPE 2>/dev/null \
    | awk '$4=="disk" && $3!="" {print $3, "("$2")"}' \
    | sed 's/\\s\+/ /g')

# If MODEL column is blank (some VMs), fall back to just name and size
if [ -z "$DISKS" ]; then
    DISKS=$(lsblk -d -o NAME,SIZE,TYPE 2>/dev/null \
        | awk '$3=="disk" {print $1, "("$2")"}')
fi

# Video
VIDEO=$(lspci 2>/dev/null | grep -i "vga\|display\|3d" | cut -d: -f3 | sed 's/^ //')

# Network
GW=$(ip r | awk '/default/{print $3; exit}')
IFACE=$(ip r | awk '/default/{print $5; exit}')
IP=$(ip a show "$IFACE" 2>/dev/null | awk '/inet /{split($2,a,"/"); print a[1]; exit}')

# DNS
DNS=$(grep "^nameserver" /etc/resolv.conf 2>/dev/null | head -1 | awk '{print $2}')

# Status
USERS=$(who | awk '{print $1}' | sort -u | tr '\n' ' ' | sed 's/ $//')

# Disk space - only real mounted filesystems, skip tmpfs/devtmpfs/squashfs
DISKFREE=$(df -h -x tmpfs -x devtmpfs -x squashfs 2>/dev/null \
    | awk 'NR>1 {print $6, "free:", $4}' \
    | tr '\n' '   ')

PROCS=$(ps aux 2>/dev/null | tail -n +2 | wc -l)

LOAD=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ //')

PORTS=$(ss -tlnp 2>/dev/null \
    | awk 'NR>1{split($4,a,":"); print a[length(a)]}' \
    | sort -un | tr '\n' ',' | sed 's/,$//')

UFW=$(sudo ufw status 2>/dev/null | head -1 | awk '{print $2}')

cat <<REPORT

System Report for $HOST generated by $REPUSER, on $DATETIME

System Information
------------------
OS:           $OS
Uptime:       $UP
CPU:          $CPU
RAM:          $RAM
Disk(s):      $DISKS
Video:        $VIDEO
Host Address: $IP
Gateway IP:   $GW
DNS Server:   $DNS

System Status
-------------
Users Logged In:         $USERS
Disk Space:              $DISKFREE
Process Count:           $PROCS
Load Averages:           $LOAD
Listening Network Ports: $PORTS
UFW Status:              $UFW

REPORT
